services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/HABBTODO
  
  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
  
  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: