services:
  backend:
    image: ${DOCKER_USERNAME}/todo-server:latest
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/HABBTODO
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
    depends_on:
      - mongo
    restart: unless-stopped
  
  frontend:
    image: ${DOCKER_USERNAME}/todo-client:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
  
  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: