name: CD Pipeline

# When to run this workflow - only on main branch pushes
on:
  push:
    branches: [ main ]

jobs:
  # Build and push Docker images
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      - name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/todo-client:latest
      
      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/todo-server:latest
      
      - name: Deploy notification
        run: echo "Images pushed to Docker Hub successfully!"
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/todo-app
            curl -o deploy.sh https://raw.githubusercontent.com/0xthuve/ToDo---DevOps/main/deployment/deploy.sh
            chmod +x deploy.sh
            ./deploy.sh ${{ secrets.DOCKER_USERNAME }}
